name: Demo to github-pages

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      config: 'Release'
    strategy:
      matrix:
        dotnet: ['6.0.x']

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Restore tools
        run: dotnet tool restore
        
      - name: Install
        run: cd demo && pnpm install
      - name: Build
        run: cd demo && pnpm run build:pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: demo/dist
